### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by Taha-Alikhani** [SharifAIChallenge/AIC19-Client-Java#1]
Ba tavajoh be aks tartibe harakat manteghi be nazar miad, amma hero nemitoone harekat kone

[Pic](http://s8.picofile.com/file/8351711976/JavaError.png)
_:Nothing *:Wall -:Objective +:RespawnZone
Direction d = dir[index];
            System.out.print(h_blaster.getName()+" Is going " + d);
            world.moveHero(h_blaster, d);
            System.out.print(" " + world.getAP() + "\n");

**Comment by RuhollahSeka** [comment]
شما در یک فاز، بیش از یک دستور حرکت می‌فرستین؟

**Comment by TheNewBlood** [comment]
na, in khat tanha khatie ke too moveTurn dastoore world.moveHero toosh estefade shode

**Comment by Taha-Alikhani** [comment]
> 
> 
> شما در یک فاز، بیش از یک دستور حرکت می‌فرستین؟

na, be joz in khat hichjaye moveTurn dige world.moveHero estefade nashode

**Comment by RuhollahSeka** [comment]
در کلاس
Main.java
متغیر
GLOBAL_VERBOSE_FLAG
را
true
کنید و فایل
client.log
ساخته شده بعد از ران کلاینت رو بفرستید

**Comment by Taha-Alikhani** [comment]
[Client.log](http://s8.picofile.com/file/8351718418/client.log.html)

> 
> 
> در کلاس
> Main.java
> متغیر
> GLOBAL_VERBOSE_FLAG
> را
> true
> کنید و فایل
> client.log
> ساخته شده بعد از ران کلاینت رو بفرستید

**Comment by RuhollahSeka** [comment]
لطفا کدتون رو به آدرس زیر ایمیل کنین
r.sekaleshfar@gmail.com
