### ISSUE TITLE
عدم اجرای کد پس از اتصال به سرور

### ISSUE THREAD

**Issue by sinadalvand** [SharifAIChallenge/AIC19-Client-Java#2]
بعد از اتصال کلاینت به سرور  و چاپ مقدار کلاینت اکسپتد در سرور ، هیچ واکنشی در کلاینت نشون داده نمیشه 
یعنی بهتره بگیم متد های کلاس AI اصلا صدا زده نمیشن 

گاها هم بعد از اجرای چند باره کلاینت به صورت رندوم به درستی به سرور متصل میشه و اطلاعات تبادل میشه

**Comment by RuhollahSeka** [comment]
توجه کنید که برای اینکه بازی شروع شود، پس از اجرای سرور، باید دو کلاینت را به طور موازی اجرا کنین تا با هم بازی کنند و تنها با اجرای یک کلاینت اتفاقی نمی‌افتد
