### ISSUE TITLE
مشکل در متد getPathMoveDirection()

### ISSUE THREAD

**Issue by AmirhosseinAzimyzadeh** [SharifAIChallenge/AIC19-Client-Java#5]
**اگر در مسیر ، قهرمان هم تیمی وجود داشته باشد  (به علت اینکه دو قهرمان یک تیم نمیتوانند در یک خانه باشند )حرکت در مسیر ممکن نمیباشد**

**Comment by RuhollahSeka** [comment]
توجه کنید که چون قهرمان ها ثابت نمیمونن در نظر گرفتن جای قهرمان ها هم در این متد لزوما کار درستی نیست و به همین دلیل توجه به این نکته به کاربر واگذار شده.
به دلیل درخواست های متعدد به زودی متدی برای اون حالت هم اضافه خواهد شد

**Comment by AmirhosseinAzimyzadeh** [comment]
متد برای این حالت اضافه کردید؟؟

**Comment by RuhollahSeka** [comment]
بله، الآن علاوه بر اینکه مسیر از دیوار نمی‌گذره، می‌تونین لیستی از مکان‌هایی که نمی‌خواهید مسیر از اونا بگذرن رو ورودی بدین
