### ISSUE TITLE
blockedCell in getPathMoveDirections are not considered!!

### ISSUE THREAD

**Issue by HassanZareie** [SharifAIChallenge/AIC19-Client-Java#6]
there is no difference between getPathMoveDirections(start,end) and getPathMoveDirections(start,end,blockedCells). given path are not consider given blockedCell at all! i have try it and give my three other hero (when i want to move one) as blockedCells but it don't consider it and return a path by crossing on my heroes. thanks for solving bug!

**Comment by mo-ma** [comment]
Can you send us your code so we can check?

**Comment by HassanZareie** [comment]
> Can you send us your code so we can check?

i dont think the problem is from mine...
            `Hero[] myHeroes = world.getMyHeroes();
            for (int i = 0; i < myHeroes.length; i++) {

                ArrayList<Cell> blockedCell = new ArrayList<>();
                for (int j = 0; j < myHeroes.length; j++) {
                    if (j == i) {
                        continue;
                    }
                    blockedCell.add(myHeroes[j].getCurrentCell());
                }

                Cell startCell = myHeroes[i].getCurrentCell();
                Cell endCell = tempEnd[i];

                Direction[] p = world.getPathMoveDirections(startCell, endCell);

                try {
                    world.moveHero(myHeroes[i], p[0]);
                } catch (java.lang.ArrayIndexOutOfBoundsException e) {
                }

                consoleLogger(blockedCell, world, myHeroes, i, startCell, p, endCell);

            }`

these statement run in moveTurn() method.

**Comment by mo-ma** [comment]
You don't use the blockedCells as an argument for getPathMoveDirections in the code you commented here. If you still have problems when you do use it, can you tell me how you fill the tempEnd array and which map you're using?

**Comment by HassanZareie** [comment]
> You don't use the blockedCells as an argument for getPathMoveDirections in the code you commented here. If you still have problems when you do use it, can you tell me how you fill the tempEnd array and which map you're using?

oh! yes... i am so sorry for asking this question! i am very careless! sorry again!
