### ISSUE TITLE
باگ مقدار برگشتی متد getPathMoveDirection

### ISSUE THREAD

**Issue by amk9978** [SharifAIChallenge/AIC19-Client-Java#7]
این متد گاهی با وجود داشتن مسیر بین مبدا و مقصد نال برمیگردونه واندازه آرایه اش صفره
[graphic.log](https://github.com/SharifAIChallenge/AIC19-Client-Java/files/2871686/graphic.log)
[server_view.log](https://github.com/SharifAIChallenge/AIC19-Client-Java/files/2871690/server_view.log)

**Comment by mo-ma** [comment]
سلام. می شه کدتون رو هم بفرستید تا بررسی کنیم؟

**Comment by amk9978** [comment]
مثلا این همه کلاس AI بدون درنظر گیری متد اکشن:
`public class AI
{

    private Random random = new Random();
    private ArrayList<Cell> blocked = new ArrayList<>();
    public void preProcess(World world)
    {
        Map map = world.getMap();
        System.out.println("pre process started");
        for (int i = 0; i < 31; i++) {
            for (int j = 0; j < 31; j++) {
                if (map.getCell(i,j).isWall()){
                    blocked.add(map.getCell(i,j));
                }
            }
        }
    }

    public void pickTurn(World world)
    {
        System.out.println("pick started");
        world.pickHero(HeroName.SENTRY);
    }

    public void moveTurn(World world)
    {
        System.out.println("move started");
        Hero[] heroes = world.getMyHeroes();
        Cell target = world.getMap().getObjectiveZone()[random.nextInt(world.getMap().getObjectiveZone().length-1)];
        for (int i = 0; i < heroes.length; i++) {
            blocked.add(heroes[i].getCurrentCell());
        }
        for (Hero hero : heroes)
        {
            if (hero.getCurrentCell().isInObjectiveZone()){
                continue;
            }
            System.out.println("turn:" + world.getCurrentTurn() + ",id:" + hero.getId() + ",row:"
                    + hero.getCurrentCell().getRow() + ",col:" + hero.getCurrentCell().getColumn());
            System.out.println("target row:" + target.getRow() + ",col:" + target.getColumn());
            Direction [] directions = world.getPathMoveDirections(hero.getCurrentCell(),target,blocked);
            System.out.println("");
            world.moveHero(hero, directions[0]);
        }
        System.out.println(world.getAP());
    }`

**Comment by mo-ma** [comment]
توی اری‌لیست بلاکد تمام جاهایی که هیرو های خودی تاحالا بودن رو نگه می دارید و پاک نمی کنید جاهای نوبت های 
 قبلی رو پس از یک جایی به بعد ممکنه راهی که از اونا رد نشه وجود نداشته باشه.
همچنین لازم نیست دیوار هارو توی بلاکد قرار بدین، تابع در هر صورت مسیری میده که از دیوار ها نگذره.
