### ISSUE TITLE
i found a bug

### ISSUE THREAD

**Issue by HassanZareie** [SharifAIChallenge/AIC19-Client-Java#8]
world.isInVision(cell1, cell2) return false if cell1 & cell2 is same.

**Comment by mo-ma** [comment]
If the cell is a wall that is the intended outcome. If that's not your problem could you send us the code you are having a problem with?

**Comment by HassanZareie** [comment]
thank you but i solve my problem by checking if cell1.equals(cell2). both cell will be get from world.getmap().getObjectiveZone() so they are not wall. i think the problem is yours. you check it however.
i just inform you.
