### ISSUE TITLE
world.getMyCastAbilities()

### ISSUE THREAD

**Issue by amk9978** [SharifAIChallenge/AIC19-Client-Java#9]
سلام
چرا این متد رو هرجا صدا بزنیم سایزش صفره؟
world.getMyCastAbilities()
اصلا چطور میتوان از این استفاده کرد؟

**Comment by amk9978** [comment]
چرا برخی ترن ها بدون موو میره سراغ اکشن یهو؟
و حتی جالبه که در اول اکشن این ترن 6 
ap
برابر صفر چاپ شده!
![1](https://user-images.githubusercontent.com/35371206/53879876-ca630c80-4024-11e9-9296-6f2d9c0f3fd1.JPG)
![2](https://user-images.githubusercontent.com/35371206/53879877-ca630c80-4024-11e9-9acc-0ef9adfd2984.JPG)
![3](https://user-images.githubusercontent.com/35371206/53879878-ca630c80-4024-11e9-9227-fb741a306861.JPG)

**Comment by mo-ma** [comment]
این متد اگه در اولین موو بعد از اکشن استفاده بشه قابلیت‌های خودی که ترن قبل استفاده شده رو میده. اگه در فازهای دیگه استفاده بشه خالیه. 

برای مشکل دوم هم ربطی به کلاینت نداره احتمالا.

**Comment by amk9978** [comment]
بله بله مشکل اول رو متوجه شدم!ممنون
